title: Dasa Sathyan @ javadas Blog
author: Dasa Sathyan | javadas
email: dasasathyan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I share what I know in technology, what I know in history, what I do for fun
baseurl: https://dasasathyan.github.io/github-pages-with-jekyll/

# social links
twitter_username: dasasathyan # DO NOT include the @ character, or else the build will fail!
github_username:  dasasathyan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: hyde
